# Choose a simple unique name for your pattern
name: Example Python Pattern

# Describe your pattern in a short sentence
description: A simple example showing how to write a Python pattern

# Optionally specify your name and school/university
# Remove the lines if you do not want to include this information
author: John Doe
school: John Doe's School

# Optionally uncomment and specify the duration of your pattern in seconds
# Remove the line if your pattern does not require a specific duration
# duration: 60
