name: Linter

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  python:
    name: Lint Python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint the project with ruff check
        if: always()
        run: ruff check --output-format=github

      - name: Lint the project with ruff format
        if: always()
        run: ruff format --check

  javascript:
    name: Lint JavaScript
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint the project with Prettier
        if: always()
        run: npm run lint .
